// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp4LwCfEWt-jPEvDgyL1KtNibukuhBBrg',
    appId: '1:412365289515:web:912e093ec176fd7e6b926e',
    messagingSenderId: '412365289515',
    projectId: 'popi-38412',
    authDomain: 'popi-38412.firebaseapp.com',
    storageBucket: 'popi-38412.firebasestorage.app',
    measurementId: 'G-7F2D3V841E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi_7ZzgYeZt6KxUGIVDHxfkvGOolBgrwY',
    appId: '1:412365289515:android:1fa173711702acef6b926e',
    messagingSenderId: '412365289515',
    projectId: 'popi-38412',
    storageBucket: 'popi-38412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkGzhlZhyqbyYy9nqDoEm2WC2aXJG8RyA',
    appId: '1:412365289515:ios:9dfb2c2722c185446b926e',
    messagingSenderId: '412365289515',
    projectId: 'popi-38412',
    storageBucket: 'popi-38412.firebasestorage.app',
    iosBundleId: 'com.example.popi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkGzhlZhyqbyYy9nqDoEm2WC2aXJG8RyA',
    appId: '1:412365289515:ios:9dfb2c2722c185446b926e',
    messagingSenderId: '412365289515',
    projectId: 'popi-38412',
    storageBucket: 'popi-38412.firebasestorage.app',
    iosBundleId: 'com.example.popi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp4LwCfEWt-jPEvDgyL1KtNibukuhBBrg',
    appId: '1:412365289515:web:027ec51ccb3dc8266b926e',
    messagingSenderId: '412365289515',
    projectId: 'popi-38412',
    authDomain: 'popi-38412.firebaseapp.com',
    storageBucket: 'popi-38412.firebasestorage.app',
    measurementId: 'G-GMRW1Y560Z',
  );

}